"use client"
import { useEffect,useState } from 'react'
import { storeDate, addDays } from '@/lib/occasion-dates'
import { campaignStatus,type Campaign } from '@/lib/campaign-model'
import { OCCASION_PRESETS,presetCampaign } from '@/lib/occasion-presets'
import { Button } from './ui/button'
import { Input } from './ui/input'
import { Textarea } from './ui/textarea'
import { NativeSelect } from './ui/select'
import { OccasionPhotoPicker } from './occasion-photo-picker'
function reservationNotice(campaign: Campaign) {
 const today = storeDate()
 if (today > campaign.orderCutoff) return 'Reservations closed: order cutoff was ' + campaign.orderCutoff + '.'
 if (addDays(today, 1) > campaign.endsAt) return 'Reservations closed: the earliest pickup is ' + addDays(today, 1) + ', after this campaign ends.'
 return 'Pickup must be tomorrow or later, through the campaign end date. The order cutoff is inclusive (Las Vegas time).'
}
export function AdminOccasions({password}:{password:string}){
 const [editingItem,setEditingItem]=useState<string|null>(null)
 const [campaigns,setCampaigns]=useState<Campaign[]>([]);const [edit,setEdit]=useState<Campaign|null>(null);const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');const [year,setYear]=useState(new Date().getFullYear());const [preset,setPreset]=useState(OCCASION_PRESETS[0].id);const [images,setImages]=useState<{url:string;label:string}[]>([])
 async function api(action:string,extra:Record<string,unknown>={}){const response=await fetch('/api/admin/occasions',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({password,action,...extra})});const data=await response.json();if(!response.ok)throw new Error(data.error||'Please retry');return data}
 async function load(){try{setCampaigns((await api('list')).campaigns)}catch(e){setMessage((e as Error).message)}}
 useEffect(()=>{void load();fetch('/api/admin/occasion-images',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({password})}).then(r=>r.json()).then(d=>setImages(d.images||[])).catch(()=>{})},[password])
 async function save(published:boolean,preview=false){if(!edit)return;const tab=preview?window.open('about:blank','_blank'):null;if(tab)tab.opener=null;setBusy(true);setMessage('');try{const result=await api('save',{campaign:{...edit,published}});setEdit(result.campaign);await load();setMessage(published?'Campaign published.':'Draft saved.');if(tab)tab.location.href='/pre-order?preview='+encodeURIComponent(edit.id)}catch(e){tab?.close();setMessage((e as Error).message)}finally{setBusy(false)}}
 async function remove(c:Campaign){if(!confirm('Delete '+c.name+'? Existing orders will be kept.'))return;setBusy(true);try{await api('delete',{id:c.id});if(edit?.id===c.id)setEdit(null);await load()}catch(e){setMessage((e as Error).message)}finally{setBusy(false)}}
 async function duplicate(c:Campaign){const copy={...c,id:crypto.randomUUID(),name:c.name+' (copy)',published:false};setBusy(true);try{await api('save',{campaign:copy});setEdit(copy);await load();setMessage('Copied as a new draft. Update its dates before publishing.')}catch(e){setMessage((e as Error).message)}finally{setBusy(false)}}
 function fromPreset(){if(!Number.isInteger(year)||year<2026||year>2100){setMessage("Choose a year from 2026 to 2100.");return;}const selected=OCCASION_PRESETS.find(p=>p.id===preset)!;setEdit(presetCampaign(selected,year,edit?.id||crypto.randomUUID()));setMessage(selected.dates(year)?'Preset applied. Edit the copy and add your items.':'Set the festival dates manually for this year.');}
 function text(label:string,value:string,change:(value:string)=>void,area=false){const limits:Record<string,number>={'Campaign name':150,'Occasion':100,'Headline':160,'Message':350,'Second-language line (optional)':350,'CTA label':80,'Page title':180,'Introduction':1500,'Item name':150,'Second-language name':150};const max=limits[label];return <label className="block text-sm font-medium"><span className="mb-1 flex items-center justify-between gap-3"><span>{label}</span>{max&&<span className="text-xs font-normal tabular-nums text-muted-foreground">{value.length}/{max}</span>}</span>{area?<Textarea aria-label={label} maxLength={max} value={value} onChange={e=>change(e.target.value)}/>:<Input aria-label={label} maxLength={max} value={value} onChange={e=>change(e.target.value)}/>}</label>}

 return <section className="space-y-5"><h2 className="heading-2">Occasions</h2><p>One campaign controls the site-wide banner and reservation page. The first active campaign in this list is shown.</p><p role="status">{message}</p><Button variant="outline" onClick={load} disabled={busy}>Refresh campaigns</Button>
 <div className="grid gap-3 md:grid-cols-2">{campaigns.map(c=><article key={c.id} className="rounded-xl border bg-card p-4"><h3 className="heading-3">{c.name}</h3><p className="my-2 text-sm"><span className="rounded bg-secondary px-2 py-1">{campaignStatus(c)==='active'?'Banner active':campaignStatus(c)}</span> · {c.startsAt} – {c.endsAt}</p><p className="mb-3 text-sm text-muted-foreground">{reservationNotice(c)}</p><div className="flex flex-wrap gap-2"><Button variant="outline" disabled={busy} onClick={()=>setEdit(c)}>Edit</Button><Button variant="outline" disabled={busy} onClick={()=>duplicate(c)}>Duplicate</Button><Button variant="outline" disabled={busy} onClick={()=>remove(c)}>Delete</Button></div></article>)}</div>
 <Button disabled={busy} onClick={()=>{setEdit(presetCampaign(OCCASION_PRESETS[0],year,crypto.randomUUID()));setPreset(OCCASION_PRESETS[0].id)}}>New occasion</Button>
 {edit&&<div className="rounded-xl border bg-card p-4 sm:p-6"><h3 className="heading-3 mb-4">Edit occasion</h3><fieldset disabled={busy} className="space-y-5"><div className="grid gap-3 sm:grid-cols-2"><label>Occasion preset<NativeSelect aria-label="Occasion preset" value={preset} onChange={e=>setPreset(e.target.value)}>{OCCASION_PRESETS.map(p=><option key={p.id} value={p.id}>{p.label}</option>)}</NativeSelect></label><label>Year<Input type="number" min={2026} max={2100} value={year} onChange={e=>setYear(Number(e.target.value))}/></label></div><Button variant="outline" onClick={()=>{if(confirm('Replace this editor’s copy, dates, and items with the preset? Unsaved edits will be cleared.'))fromPreset()}}>Apply preset</Button><p className="text-sm">Second-language hint: {OCCASION_PRESETS.find(p=>p.id===preset)?.language||'optional'}. All text and dates below are editable.</p>
 {text('Campaign name',edit.name,v=>setEdit({...edit,name:v}))}{text('Occasion',edit.occasion,v=>setEdit({...edit,occasion:v}))}
 <div className="grid gap-3 sm:grid-cols-3">{(['startsAt','endsAt','orderCutoff'] as const).map(key=><label key={key}>{{startsAt:'Banner starts',endsAt:'Campaign ends',orderCutoff:'Order cutoff'}[key]}<Input type="date" value={edit[key]} onChange={e=>setEdit({...edit,[key]:e.target.value})}/></label>)}</div>
 <p role="status" className="rounded-lg border bg-secondary p-3 text-sm">{reservationNotice(edit)} {addDays(storeDate(),1)>edit.endsAt && "There are no future pickup dates left in this campaign."}</p>
 <h4 className="font-semibold">Banner</h4>{text('Headline',edit.banner.headline,v=>setEdit({...edit,banner:{...edit.banner,headline:v}}))}{text('Message',edit.banner.message,v=>setEdit({...edit,banner:{...edit.banner,message:v}}),true)}{text('Second-language line (optional)',edit.banner.subline||'',v=>setEdit({...edit,banner:{...edit.banner,subline:v}}))}{text('CTA label',edit.banner.ctaLabel,v=>setEdit({...edit,banner:{...edit.banner,ctaLabel:v}}))}
 <h4 className="font-semibold">Pre-order page</h4>{text('Page title',edit.page.title,v=>setEdit({...edit,page:{...edit.page,title:v}}))}{text('Introduction',edit.page.intro,v=>setEdit({...edit,page:{...edit.page,intro:v}}),true)}<OccasionPhotoPicker label="Hero image" value={edit.page.heroImage} password={password} images={images} onChange={v=>setEdit({...edit,page:{...edit.page,heroImage:v}})}/>
 <h4 className="font-semibold">Items</h4>{edit.items.map((item,index)=>{const change=(patch:Partial<Campaign['items'][number]>)=>setEdit({...edit,items:edit.items.map((row,i)=>i===index?{...row,...patch}:row)});return <div key={item.id} className="space-y-3 rounded-lg border p-4"><div className="flex flex-wrap items-center gap-3">{item.photo?<img src={item.photo} alt="" width={64} height={64} className="h-16 w-16 shrink-0 rounded-lg object-cover"/>:<div aria-hidden="true" className="flex h-16 w-16 shrink-0 items-center justify-center rounded-lg bg-secondary text-sm text-primary">Photo</div>}<div className="min-w-0 flex-1"><p className="break-words font-semibold">{item.name||'New item'}</p><p className="text-sm text-primary">$ {item.price.toFixed(2)}</p></div><div className="flex gap-2"><Button variant="outline" aria-expanded={editingItem===item.id} aria-label={'Edit '+(item.name||'new item')} onClick={()=>setEditingItem(editingItem===item.id?null:item.id)}>Edit</Button><Button variant="outline" aria-label={'Remove '+(item.name||'new item')} onClick={()=>setEdit({...edit,items:edit.items.filter((_,i)=>i!==index)})}>Remove</Button></div></div><div hidden={editingItem!==item.id} className="space-y-3 border-t pt-4">{text('Item name',item.name,v=>change({name:v}))}{text('Second-language name',item.nameAlt||'',v=>change({nameAlt:v}))}<div className="grid gap-3 sm:grid-cols-2"><label>Price ($)<Input type="number" step="0.01" min="0.01" value={item.price||''} onChange={e=>change({price:Number(e.target.value)})}/></label><label>Maximum per order (optional)<Input type="number" min={1} max={999} value={item.maxPerOrder??''} onChange={e=>change({maxPerOrder:e.target.value?Number(e.target.value):undefined})}/></label></div><OccasionPhotoPicker label="Item photo" value={item.photo} password={password} images={images} onChange={v=>change({photo:v})}/><Button variant="outline" onClick={()=>setEditingItem(null)}>Done editing item</Button></div></div>})}<Button variant="outline" onClick={()=>{const id=crypto.randomUUID();setEdit({...edit,items:[...edit.items,{id,name:'',price:0}]});setEditingItem(id)}}>Add item</Button>
 <div className="sticky bottom-0 z-30 grid grid-cols-2 gap-3 rounded-lg border bg-background p-3 shadow-sm sm:flex sm:flex-wrap"><Button variant="outline" onClick={()=>save(false)}>Save draft</Button><Button variant="outline" onClick={()=>save(edit.published,true)}>Save & preview</Button><Button onClick={()=>save(!edit.published)}>{edit.published?'Unpublish':'Publish'}</Button><Button variant="outline" onClick={()=>setEdit(null)}>Close editor</Button></div><p className="text-sm">Save draft switches a published campaign off. Preview saves your changes but keeps its current publication status. Empty campaigns show a call option until items are added.</p></fieldset></div>}
 </section>
}
