"use client"
import { useEffect,useState } from 'react'
import { orderStatuses,type PreOrder } from '@/lib/pre-order'
import { Button } from './ui/button'
import { NativeSelect } from './ui/select'
export function AdminPreOrders({password}:{password:string}){const [orders,setOrders]=useState<PreOrder[]>([]);const [error,setError]=useState('');const [busy,setBusy]=useState(false)
 async function request(extra:Record<string,unknown>){const r=await fetch('/api/admin/pre-orders',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({password,...extra})});const data=await r.json();if(!r.ok)throw new Error(data.error);return data}
 async function load(){setBusy(true);try{setOrders((await request({action:'list'})).orders);setError('')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 useEffect(()=>{void load()},[password]);async function status(id:string,value:string){setBusy(true);try{await request({action:'status',id,status:value});await load()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 return <section className="space-y-4"><h2 className="heading-2">Pre-orders</h2><Button variant="outline" onClick={load} disabled={busy}>Refresh orders</Button><p role="alert">{error}</p>{!orders.length&&!error&&<p>No reservation requests yet.</p>}<div className="grid gap-4 lg:grid-cols-2">{orders.map(order=><article key={order.id} className="min-w-0 rounded-xl border bg-card p-4"><h3 className="heading-3">{order.name}</h3><dl className="my-3 space-y-2 break-words"><div><dt className="font-semibold">Campaign</dt><dd>{order.campaignName}</dd></div><div><dt className="font-semibold">Received</dt><dd>{new Date(order.createdAt).toLocaleString('en-US',{timeZone:'America/Los_Angeles'})} (Las Vegas)</dd></div><div><dt className="font-semibold">Contact</dt><dd><a className="inline-flex min-h-12 items-center underline" href={'tel:'+order.phone.replace(/[^+0-9]/g,'')}>{order.phone}</a>{order.email&&<p>{order.email}</p>}</dd></div><div><dt className="font-semibold">Items</dt><dd>{order.items.map(i=><p key={i.itemId}>{i.qty} × {i.name} @ $ {i.price.toFixed(2)}</p>)}</dd></div><div><dt className="font-semibold">Pickup date / fulfillment</dt><dd>{order.pickupDate} · {order.fulfillment}</dd></div><div><dt className="font-semibold">Notes</dt><dd>{order.notes||'None'}</dd></div></dl><label htmlFor={"order-status-"+order.id}>Status</label><NativeSelect id={"order-status-"+order.id} value={order.status} disabled={busy} onChange={e=>status(order.id,e.target.value)}>{orderStatuses.map(s=><option key={s} value={s}>{s.replace('_',' ')}</option>)}</NativeSelect></article>)}</div></section>
}
