"use client"
import { useState } from 'react'
import { Input } from './ui/input'
import { Button } from './ui/button'
export function OccasionPhotoPicker({label,value,onChange,password,images}:{label:string;value?:string;onChange:(url:string)=>void;password:string;images:{url:string;label:string}[]}){
 const [open,setOpen]=useState(false);const [busy,setBusy]=useState(false);const [error,setError]=useState('')
 async function upload(file:File){setBusy(true);setError('');try{const form=new FormData();form.set('password',password);form.set('file',file);const response=await fetch('/api/gallery/upload',{method:'POST',body:form});const data=await response.json();if(!response.ok)throw new Error(response.status>=500?'Photo uploads need the Blob store connected — see docs/OCCASIONS.md':data.error||'Upload failed');onChange(data.url)}catch(e){const message=e instanceof Error?e.message:'Upload failed';setError(/blob|sdk|token/i.test(message)?'Photo uploads need the Blob store connected — see docs/OCCASIONS.md':message)}finally{setBusy(false)}}
 return <div className="space-y-2"><label className="block text-sm font-medium">{label}<Input value={value||''} onChange={e=>onChange(e.target.value)} placeholder="Image URL (optional)"/></label>{value&&<img src={value} alt={label+' preview'} width={160} height={120} className="h-24 w-32 rounded-lg object-cover"/>}<div className="flex flex-wrap gap-2"><Button type="button" variant="outline" onClick={()=>setOpen(!open)}>Pick existing photo</Button><label className="inline-flex min-h-12 cursor-pointer items-center rounded-lg border px-4 focus-within:outline-2 focus-within:outline-primary">{busy?'Uploading…':'Upload photo'}<input className="sr-only" type="file" accept="image/jpeg,image/png,image/webp,image/gif" disabled={busy} onChange={e=>{const file=e.target.files?.[0];if(file)void upload(file);e.target.value=''}}/></label>{value&&<Button type="button" variant="outline" onClick={()=>onChange('')}>Clear photo</Button>}</div><p role="alert">{error}</p>{open&&<div className="grid max-h-64 grid-cols-3 gap-2 overflow-auto rounded-lg border p-2">{images.map((image,index)=><button key={image.url+index} type="button" className="rounded border p-1 text-left text-xs" onClick={()=>{onChange(image.url);setOpen(false)}}><img src={image.url} alt={image.label} loading="lazy" width={160} height={100} className="aspect-[8/5] w-full object-cover"/><span>{image.label}</span></button>)}</div>}</div>
}
